import type { Metadata } from "next";
import { BIZ_UDPGothic} from "next/font/google";
import "./globals.css";

const Biz = BIZ_UDPGothic({
  variable: "--font-biz-udpgothic",
  weight: ["400", "700"],
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Biz.variable}`}>
        {children}
      </body>
    </html>
  );
}
